<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OfficeCollabServer.FssHttp\OfficeCollabServer.FssHttp.csproj" />
    <ProjectReference Include="..\OfficeCollabServer.FssHttpB\OfficeCollabServer.FssHttpB.csproj" />
    <ProjectReference Include="..\OfficeCollabServer.Storage\OfficeCollabServer.Storage.csproj" />
    <ProjectReference Include="..\OfficeCollabServer.ServiceDefaults\OfficeCollabServer.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
