<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../CellBridge.AspNetCore/CellBridge.AspNetCore.csproj" />
    <ProjectReference Include="../CellBridge.Storage.InMemory/CellBridge.Storage.InMemory.csproj" />
    <ProjectReference Include="../CellBridge.Storage.PostgreSql/CellBridge.Storage.PostgreSql.csproj" />
    <ProjectReference Include="../CellBridge.Storage.FileSystem/CellBridge.Storage.FileSystem.csproj" />
    <ProjectReference Include="..\CellBridge.FssHttp\CellBridge.FssHttp.csproj" />
    <ProjectReference Include="..\CellBridge.FssHttpB\CellBridge.FssHttpB.csproj" />
    <ProjectReference Include="..\CellBridge.Storage\CellBridge.Storage.csproj" />
    <ProjectReference Include="..\CellBridge.ServiceDefaults\CellBridge.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup><ProjectReference Include="../CellBridge.Authentication/CellBridge.Authentication.csproj" /></ItemGroup>
  <ItemGroup><PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" /></ItemGroup>
</Project>
