#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class CentralDirectoryDigitalSignature : BaseStructure
    {
        /*
        Digital signature:
        header signature                4 bytes  (0x05054b50)
        size of data                    2 bytes
        signature data (variable size)
         *
         * */

        public Int32 HeaderSignature;
        public short SizeOfData;
        public byte[] SignatureData;

        /// <summary>
        /// Parse the CentralDirectoryFileHeader structure.
        /// </summary>
        /// <param name="s">A stream containing CentralDirectoryFileHeader structure.</param>
        public override void Parse(Stream s)
        {
            base.Parse(s);
            this.HeaderSignature = ReadINT32();
            this.SizeOfData = ReadINT16();
            if (this.SizeOfData > 0)
            {
                this.SignatureData = ReadBytes(this.SizeOfData);
            }
        }
    }
}
