#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class CentralDirectoryFileHeader : BaseStructure
    {
        /*
        central file header signature   4 bytes  (0x02014b50)
        version made by                 2 bytes
        version needed to extract       2 bytes
        general purpose bit flag        2 bytes
        compression method              2 bytes
        last mod file time              2 bytes
        last mod file date              2 bytes
        crc-32                          4 bytes
        compressed size                 4 bytes
        uncompressed size               4 bytes
        file name length                2 bytes
        extra field length              2 bytes
        file comment length             2 bytes
        disk number start               2 bytes
        internal file attributes        2 bytes
        external file attributes        4 bytes
        relative offset of local header 4 bytes

        file name (variable size)
        extra field (variable size)
        file comment (variable size)
         *
         * */
        public Int32 CentralFileHeaderSignature;
        public short VersionMadeBy;
        public short VersionNeededToExtract;
        public short GeneralPurposeBitFlag;
        public short CompressionMethod;
        public short LastModFileTime;
        public short LastModFileDate;
        public Int32 Crc32;
        public Int32 CompressedSize;
        public Int32 UncompressedSize;
        public short FileNameLength;
        public short ExtraFieldLength;
        public short FileCommentLength;
        public short DiskNumberStart;
        public short InternalFileAttributes;
        public Int32 ExternalFileAttributes;
        public Int32 RelativeOffsetOfLocalHeader;
        public byte[] FileName;
        public byte[] ExtraField;
        public byte[] FileComment;

        /// <summary>
        /// Parse the CentralDirectoryFileHeader structure.
        /// </summary>
        /// <param name="s">A stream containing CentralDirectoryFileHeader structure.</param>
        public override void Parse(Stream s)
        {
            base.Parse(s);
            this.CentralFileHeaderSignature = ReadINT32();
            this.VersionMadeBy = ReadINT16();
            this.VersionNeededToExtract = ReadINT16();
            this.GeneralPurposeBitFlag = ReadINT16();
            this.CompressionMethod = ReadINT16();
            this.LastModFileTime = ReadINT16();
            this.LastModFileDate = ReadINT16();
            this.Crc32 = ReadINT32();
            this.CompressedSize = ReadINT32();
            this.UncompressedSize = ReadINT32();
            this.FileNameLength = ReadINT16();
            this.ExtraFieldLength = ReadINT16();
            this.FileCommentLength = ReadINT16();
            this.DiskNumberStart = ReadINT16();
            this.InternalFileAttributes = ReadINT16();
            this.ExternalFileAttributes = ReadINT32();
            this.RelativeOffsetOfLocalHeader = ReadINT32();
            if (this.FileNameLength > 0)
            {
                this.FileName = ReadBytes(this.FileNameLength);
            }

            if (this.ExtraFieldLength > 0)
            {
                this.ExtraField = ReadBytes(this.ExtraFieldLength);
            }

            if (this.FileCommentLength > 0)
            {
                this.FileComment = ReadBytes(this.FileCommentLength);
            }
        }

    }
}
