#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class CentralDirectoryStructure : BaseStructure
    {
        public CentralDirectoryFileHeader[] fileHeader;
        public CentralDirectoryDigitalSignature digitalSignature;
        public override void Parse(Stream s)
        {
            base.Parse(s);
            List<CentralDirectoryFileHeader> fileHeaderTemp = new List<CentralDirectoryFileHeader>();
            while (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.CentralDirectoryHeader))
            {

                CentralDirectoryFileHeader header = new CentralDirectoryFileHeader();
                header.Parse(s);
                fileHeaderTemp.Add(header);
            }

            fileHeader = fileHeaderTemp.ToArray();
            if (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.SignatureCentralDirectory))
            {
                digitalSignature.Parse(s);
            }
        }
    }
}
