#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class EndOfCentralDirectoryRecord : BaseStructure
    {
        /*
         *
        end of central dir signature                                           4 bytes  (0x06054b50)
        number of this disk                                                    2 bytes
        number of the disk with the start of the central directory             2 bytes
        total number of entries in the central directory on this disk          2 bytes
        total number of entries in the central directory                       2 bytes
        size of the central directory                                          4 bytes
        offset of start of central directory with respect to the starting disk number        4 bytes
        .ZIP file comment length                                               2 bytes
        .ZIP file comment                                                      (variable size)

         * */
        public Int32 EndOfCentralDirSignature;
        public short NumberOfThisDisk;
        public short NumberOfThisDiskWithTheStartOfTheCentralDirectory;
        public short TotalNumberOfEntriesInTheCentralDirectoryOnThisDisk;
        public short TotalNumberOfEntriesInTheCentralDirectory;
        public Int32 SizeOfTheCentralDirectory;
        public Int32 OffsetOfStartOfCentralDirectoryWithRespectToTheStartingDiskNumber;
        public Int16 ZipFileCommentLength;
        public byte[] ZipFileComment;

        /// <summary>
        /// Parse the EndOfCentralDirectoryRecord structure.
        /// </summary>
        /// <param name="s">A stream containing EndOfCentralDirectoryRecord structure.</param>
        public override void Parse(Stream s)
        {
            base.Parse(s);
            this.EndOfCentralDirSignature = ReadINT32();
            this.NumberOfThisDisk = ReadINT16();
            this.NumberOfThisDiskWithTheStartOfTheCentralDirectory = ReadINT16();
            this.TotalNumberOfEntriesInTheCentralDirectoryOnThisDisk = ReadINT16();
            this.TotalNumberOfEntriesInTheCentralDirectory = ReadINT16();
            this.SizeOfTheCentralDirectory = ReadINT32();
            this.OffsetOfStartOfCentralDirectoryWithRespectToTheStartingDiskNumber = ReadINT32();
            this.ZipFileCommentLength = ReadINT16();
            if (this.ZipFileCommentLength > 0)
            {
                this.ZipFileComment = ReadBytes(this.ZipFileCommentLength);
            }
        }
    }
}
