#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class LocalFileHeader : BaseStructure
    {
        public Int32 LocalFileHeaderSignature;
        public short VersionNeededToExtract;
        public short GeneralPurposeBitFlag;
        public short CompressionMethod;
        public short LastModFileTime;
        public short LastModFileDate;
        public Int32 Crc32;
        public Int32 CompressedSize;
        public Int32 UncompressedSize;
        public short FileNameLength;
        public short ExtraFieldLength;
        public string FileName;
        public byte[] ExtraField;
        public byte[] FileData;
        public byte[] Signature;
        public Int32? Crc32_descriptor;
        public Int32? CompressedSize_descriptor;
        public Int32? UncompressedSize_descriptor;

        /// <summary>
        /// Parse the LocalFileHeader structure.
        /// </summary>
        /// <param name="s">A stream containing LocalFileHeader structure.</param>
        public override void Parse(Stream s)
        {
            base.Parse(s);
            this.LocalFileHeaderSignature = ReadINT32();
            this.VersionNeededToExtract = ReadINT16();
            byte temp = CurrentByte();
            this.GeneralPurposeBitFlag = ReadINT16();
            this.CompressionMethod = ReadINT16();
            this.LastModFileTime = ReadINT16();
            this.LastModFileDate = ReadINT16();
            this.Crc32 = ReadINT32();
            this.CompressedSize = ReadINT32();
            this.UncompressedSize = ReadINT32();
            this.FileNameLength = ReadINT16();
            this.ExtraFieldLength = ReadINT16();
            if (this.FileNameLength > 0)
            {
                this.FileName = ReadString(System.Text.Encoding.UTF8, "", FileNameLength);
            }

            if (this.ExtraFieldLength > 0)
            {
                this.ExtraField = ReadBytes((int)ExtraFieldLength);
            }

            if (this.CompressedSize > 0 && (30 + this.CompressedSize) <= 4096)//1048576
            {
                this.FileData = ReadBytes((int)CompressedSize);
            }
            if (GetBits(temp, 3, 1) == 1)
            {
                if (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.SignatureDataDescriptor))
                {
                    Signature = ReadBytes(4);
                }
                Crc32_descriptor = ReadINT32();
                CompressedSize_descriptor = ReadINT32();
                UncompressedSize_descriptor = ReadINT32();
            }
        }
    }
}
