#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class Zip64endOfCentralDirectoryLocator : BaseStructure
    {
        /*
         *
        zip64 end of central dir locator signature                                         4 bytes  (0x07064b50)
        number of the disk with the start of the zip64 end of central directory            4 bytes
        relative offset of the zip64 end of central directory record                       8 bytes
        total number of disks                                                              4 bytes
         * */
        public Int32 Zip64EndOfCentralDirLocatorSignature;
        public Int32 NumberOfTheDiskWithTheStartOfTheZip64EndOfCentralDirectory;
        public long RelativeOffsetOfTheZip64EndOfCentralDirectoryRecord;
        public Int32 TotalNumberOfDisks;

        /// <summary>
        /// Parse the Zip64endOfCentralDirectoryLocator structure.
        /// </summary>
        /// <param name="s">A stream containing Zip64endOfCentralDirectoryLocator structure.</param>
        public override void Parse(Stream s)
        {
            base.Parse(s);
            this.Zip64EndOfCentralDirLocatorSignature = ReadINT32();
            this.NumberOfTheDiskWithTheStartOfTheZip64EndOfCentralDirectory = ReadINT32();
            this.RelativeOffsetOfTheZip64EndOfCentralDirectoryRecord = ReadINT64();
            this.TotalNumberOfDisks = ReadINT32();
        }
    }
}
