#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class Zip64EndOfCentralDirectoryRecord : BaseStructure
    {
        /*
         * Zip64 end of central directory record
         * zip64 end of central dir signature                       4 bytes  (0x06064b50)
        size of zip64 end of central directory record                8 bytes
        version made by                 2 bytes
        version needed to extract       2 bytes
        number of this disk             4 bytes
        number of the disk with the start of the central directory  4 bytes
        total number of entries in the central directory on this disk  8 bytes
        total number of entries in the central directory               8 bytes
        size of the central directory   8 bytes
        offset of start of central directory with respect to the starting disk number        8 bytes
        zip64 extensible data sector    (variable size)

         *
         * */

        public Int32 Zip64EndOfCentralDirSignature;
        public long SizeOfZip64EndOfCentralDirectoryRecord;
        public short VersionMadeBy;
        public short VersionNeededToExtract;
        public Int32 NumberOfThisDisk;
        public Int32 NumberOfTheDiskWithTheStartOfTheCentralDirectory;
        public long TotalNumberOfEntriesInTheCentralDirectoryOnThisDisk;
        public long TotalNumberOfEntriesInTheCentralDirectory;
        public long SizeOfTheCentralDirectory;
        public long OffsetOfStartOfCentralDirectoryWithRespectToTheStartingDiskNumber;
        public byte[] Zip64ExtensibleDataSector;

        /// <summary>
        /// Parse the Zip64EndOfCentralDirectoryRecord structure.
        /// </summary>
        /// <param name="s">A stream containing Zip64EndOfCentralDirectoryRecord structure.</param>
        public override void Parse(Stream s)
        {
            base.Parse(s);
            this.Zip64EndOfCentralDirSignature = ReadINT32();
            this.SizeOfZip64EndOfCentralDirectoryRecord = ReadINT64();
            this.VersionMadeBy = ReadINT16();
            this.VersionNeededToExtract = ReadINT16();
            this.NumberOfThisDisk = ReadINT32();
            this.NumberOfTheDiskWithTheStartOfTheCentralDirectory = ReadINT32();
            this.TotalNumberOfEntriesInTheCentralDirectoryOnThisDisk = ReadINT64();
            this.TotalNumberOfEntriesInTheCentralDirectory = ReadINT64();
            this.SizeOfTheCentralDirectory = ReadINT64();
            this.OffsetOfStartOfCentralDirectoryWithRespectToTheStartingDiskNumber = ReadINT64();
            long length = this.SizeOfZip64EndOfCentralDirectoryRecord - 12 - 40;
            if (length > 0)
            {
                this.Zip64ExtensibleDataSector = ReadBytes((int)length);
            }
        }
    }
}
