#nullable disable
// Ported from OfficeDev/Office-Inspectors-for-Fiddler. See NOTICE.md in this project.
//-----------------------------------------------------------------------
// Copyright (c) 2013 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized
// to use this sample source code. For the terms of the license, please see the
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------
//-----------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------

namespace CellBridge.OfficeInspectors.Parsers
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public class ZIPFileStructure : BaseStructure
    {
        public LocalFileHeader[] fileHeader;
        public ArchiveExtraDataRecord archiveExtraDataRecord;
        public CentralDirectoryStructure centralDirectory;
        public Zip64EndOfCentralDirectoryRecord zip64EndOfCentralDirectoryRecord;
        public Zip64endOfCentralDirectoryLocator zip64EndOfCentralDirectoryLocator;
        public EndOfCentralDirectoryRecord endOfCentralDirectoryRecord;

        /// <summary>
        /// Parse the ZIPFileStructure structure.
        /// </summary>
        /// <param name="s">A stream containing ZIPFileStructure structure.</param>
        public override void Parse(Stream s)
        {
            base.Parse(s);
            long startStreamPosition = s.Position;
            List<LocalFileHeader> headers = new List<LocalFileHeader>();
            while (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.LocalFileHeader))
            {
                LocalFileHeader localFileHeader = new LocalFileHeader();
                localFileHeader.Parse(s);
                headers.Add(localFileHeader);
            }
            fileHeader = headers.ToArray();

            if (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.ArchiveExtralDataRecord))
            {
                archiveExtraDataRecord = new ArchiveExtraDataRecord();
                archiveExtraDataRecord.Parse(s);
            }

            if (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.CentralDirectoryHeader))
            {
                centralDirectory = new CentralDirectoryStructure();
                centralDirectory.Parse(s);
            }

            if (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.ZIP64EndOfCentralDirectoryRecord))
            {
                zip64EndOfCentralDirectoryRecord = new Zip64EndOfCentralDirectoryRecord();
                zip64EndOfCentralDirectoryRecord.Parse(s);
            }

            if (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.ZIP64EndOfCentralDirectoryLocator))
            {
                zip64EndOfCentralDirectoryLocator = new Zip64endOfCentralDirectoryLocator();
                zip64EndOfCentralDirectoryLocator.Parse(s);
            }

            if (Utilities.IsZIPFileHeaderMatch(NextFourBytes(), Utilities.EndOfCentralDirectoryLocator))
            {
                endOfCentralDirectoryRecord = new EndOfCentralDirectoryRecord();
                endOfCentralDirectoryRecord.Parse(s);
            }
        }
    }
}
